-- AllPrints.lean: generated at build; imports every Core module and prints every terminal.
import AlternationShadow
import SignTransferShadow
import AdelicPlaneShadow
import ReDerivationShadow
import ScopeConditionShadow
import WarrantSumShadow
import SeparationShadow
import FamilySignShadow
import DependenceShadow
import SectorNonvanishingShadow
import SectorOccupancyShadow
import RefinementArityShadow
import DoubleEntryShadow
import ShareDependenceShadow
import ApportionmentShadow
import BallPairShadow
import BridgeShadow
import CharacterSumShadow
import CoherenceShadow
import ConstructorShadow
import CouplingArrival
import CriticalPassShadow
import CrossPlaceShadow
import DFTChart
import DeficitShadow
import DeterminationShadow
import DiagonalSection
import E1UnitPurityDraft
import ExtensionShadow
import FlatnessShadow
import FourthVisitShadow
import FrameBoundaryShadow
import GroupRingGlue
import H1Mechanism
import InvolutionScalarShadow
import InequalityShadow
import KLSilence
import LefschetzShadow
import LinkShadow
import MechanismShadow
import MetaplecticRootShadow
import NeitherPolesNorZeros
import NormalizationForced
import OddPInstances
import OddPairingShadow
import OrbitDictionary
import OrientationShadow
import PairingShadow
import PhasePlaneShadow
import PlancherelShadow
import ProductLawShadow
import ProductMinusSumShadow
import QuotientLemmaShadow
import QuotientWeilShape
import RadializationShadow
import RigidityShadow
import SectorArithmetic
import SilenceOnlyIfShadow
import StaircaseAddresses
import TensorSquareShadow
import ThetaBridgeShadow
import ThetaContinuationShadow
import ThetaShadow
import TowerInstance
import TowerLimitShadow
import TowerMonotoneShadow
import TraceSilence
import TwistedRootShadow
import TwistedShadow
import ValueShadow
import WindowShadow

#print axioms ReDerivationShadow.expanding_the_scaling_operator_reconciles_all_three_terms
#print axioms ReDerivationShadow.the_unexpanded_form_does_not_match
#print axioms ScopeConditionShadow.containment_holds_only_at_the_smallest_cell
#print axioms ScopeConditionShadow.the_length_bound_fails_at_every_cell
#print axioms ScopeConditionShadow.the_smallest_cell_sits_exactly_on_the_containment_edge
#print axioms WarrantSumShadow.warrant_sum_and_its_convergence
#print axioms WarrantSumShadow.mode_truncation_is_inert_here
#print axioms WarrantSumShadow.the_two_weights_are_different_objects
#print axioms SeparationShadow.void_gate_cannot_see_either_share
#print axioms SeparationShadow.divergent_share_fixed_leaves_the_remainder_free
#print axioms SeparationShadow.the_two_shares_are_independent_coordinates
#print axioms SeparationShadow.degenerate_case_stated_not_hidden
#print axioms FamilySignShadow.pairings_all_negative_and_slopes_all_positive
#print axioms FamilySignShadow.binding_cell_is_the_smallest
#print axioms FamilySignShadow.holds_at_b38_member_and_at_one_fails_at_zero
#print axioms FamilySignShadow.threshold_brackets_the_endpoint
#print axioms DependenceShadow.shift_law_is_additive
#print axioms DependenceShadow.signs_are_mixed_at_b38_member
#print axioms DependenceShadow.signs_are_uniform_off_the_window
#print axioms DependenceShadow.psi_zero_line_reproduces_the_bank
#print axioms AlternationShadow.flip_alternates_at_0
#print axioms AlternationShadow.const1_fails_at_0
#print axioms AlternationShadow.signs_distinct
#print axioms AlternationShadow.alternates_neg
#print axioms AlternationShadow.alternates_both
#print axioms AlternationShadow.alternates_both'
#print axioms AlternationShadow.both_values_survive_global_sign
#print axioms InvolutionScalarShadow.both_signs_satisfy
#print axioms InvolutionScalarShadow.others_fail
#print axioms InvolutionScalarShadow.signs_distinct
#print axioms InvolutionScalarShadow.nat_sq_one
#print axioms InvolutionScalarShadow.int_sq_one
#print axioms InvolutionScalarShadow.int_sq_one_of
#print axioms SectorNonvanishingShadow.arrival_rhs_zero
#print axioms SectorNonvanishingShadow.arrival_dim_zero
#print axioms SectorNonvanishingShadow.arrival_shape
#print axioms SectorNonvanishingShadow.banked_place2_cells
#print axioms SectorNonvanishingShadow.banked_odd_cells
#print axioms SectorNonvanishingShadow.pos_of_four_mul_pos
#print axioms SectorNonvanishingShadow.odd_rhs_pos
#print axioms SectorNonvanishingShadow.place2_rhs_pos
#print axioms SectorNonvanishingShadow.odd_sector_pos
#print axioms SectorNonvanishingShadow.place2_sector_pos
#print axioms SectorOccupancyShadow.layer_occupies_only_two_of_four_sectors
#print axioms SectorOccupancyShadow.sector_parity_is_index_parity
#print axioms RefinementArityShadow.two_fold_aggregate_does_not_determine_four_fold
#print axioms DoubleEntryShadow.column_enters_twice_net_q_minus_p
#print axioms DoubleEntryShadow.zero_share_has_no_double_entry
#print axioms ShareDependenceShadow.share_dependence_is_exactly_R
#print axioms ShareDependenceShadow.gauge_iff_R_zero
#print axioms ShareDependenceShadow.at_most_one_share_zeroes_it
#print axioms ShareDependenceShadow.no_single_share_serves_two_cells
#print axioms ApportionmentShadow.void_gate_is_exactly_normalization
#print axioms ApportionmentShadow.gate_verdict_both_polarities
#print axioms ApportionmentShadow.sector_freedom_is_one_scalar
#print axioms ApportionmentShadow.within_sector_reshuffle_invisible
#print axioms AdelicPlaneShadow.torus_gluing_instances
#print axioms AdelicPlaneShadow.hcoh_fin_instances
#print axioms AdelicPlaneShadow.stationary_dimension_instances
#print axioms AdelicPlaneShadow.visibility_split_instances
#print axioms AdelicPlaneShadow.deficit_global_minus_local
#print axioms AdelicPlaneShadow.q_triviality_instances
#print axioms BallPairShadow.sonin_dim_inclusion_exclusion
#print axioms BallPairShadow.constraint_span_dims
#print axioms BridgeShadow.mirror_shadow_9
#print axioms BridgeShadow.mirror_shadow_25
#print axioms BridgeShadow.mirror_gauss_values
#print axioms BridgeShadow.round_trip_shadow_9
#print axioms CharacterSumShadow.halc
#print axioms CharacterSumShadow.hza
#print axioms CharacterSumShadow.hnzero
#print axioms CharacterSumShadow.sh
#print axioms CharacterSumShadow.ich
#print axioms CharacterSumShadow.ich'
#print axioms CharacterSumShadow.cancel2
#print axioms CharacterSumShadow.dp
#print axioms CharacterSumShadow.sp
#print axioms CharacterSumShadow.subsub
#print axioms CharacterSumShadow.final4
#print axioms CharacterSumShadow.lemA
#print axioms CharacterSumShadow.lemD
#print axioms CharacterSumShadow.lemB
#print axioms CharacterSumShadow.lemC
#print axioms CharacterSumShadow.pconj_mul
#print axioms CharacterSumShadow.inv0
#print axioms CharacterSumShadow.inv2
#print axioms CharacterSumShadow.inv1
#print axioms CharacterSumShadow.prod3_eq_conj_prod1
#print axioms CharacterSumShadow.character_sum_general
#print axioms CharacterSumShadow.banked_roster_instances
#print axioms CoherenceShadow.reciprocity_instances
#print axioms CoherenceShadow.orientation_discriminator_2_1
#print axioms CoherenceShadow.conjugate_complement_instances
#print axioms ConstructorShadow.point_count_identity_25
#print axioms ConstructorShadow.shift_shadow_25
#print axioms ConstructorShadow.silhouette_exam
#print axioms ConstructorShadow.defect_vector_identity
#print axioms CouplingArrival.label_norm_150
#print axioms CouplingArrival.arrival_multiplicative_150
#print axioms CouplingArrival.spectrum_150
#print axioms CouplingArrival.added_place_identity
#print axioms CriticalPassShadow.monomial_trace_fixed_phase
#print axioms CriticalPassShadow.row47_corollary_2_1
#print axioms CriticalPassShadow.row47_corollary_3_1
#print axioms CriticalPassShadow.gauge_covariance_2_1
#print axioms CrossPlaceShadow.flat_place_collapse
#print axioms CrossPlaceShadow.collapse_instances
#print axioms CrossPlaceShadow.banked_globals
#print axioms DFTChart.orthogonality_5
#print axioms DFTChart.orthogonality_3
#print axioms DFTChart.orthogonality_7
#print axioms DFTChart.parity_involution
#print axioms DeficitShadow.closed_form_instances
#print axioms DeficitShadow.even_place_d1_law
#print axioms DeficitShadow.odd_flatness_d1
#print axioms DeterminationShadow.determination
#print axioms DeterminationShadow.banked_coverage_instance
#print axioms DeterminationShadow.determination_at_banked
#print axioms DiagonalSection.f_ball_zero
#print axioms DiagonalSection.hat_f_ball_zero
#print axioms DiagonalSection.transform_eigen
#print axioms DiagonalSection.fV_is_f
#print axioms DiagonalSection.parity_f
#print axioms DiagonalSection.gram_cell
#print axioms DiagonalSection.gram_cell_nonzero
#print axioms DiagonalSection.twisted_hermitian_cell
#print axioms DiagonalSection.spectrum_411
#print axioms DiagonalSection.spectrum_nonzero
#print axioms DiagonalSection.C_symmetric
#print axioms DiagonalSection.C_radical_zero
#print axioms DiagonalSection.trace_identity
#print axioms DiagonalSection.label_norm_is_coupling
#print axioms DiagonalSection.antipode_involution
#print axioms DiagonalSection.antipode_fixes_class_gram
#print axioms E1UnitPurityDraft.death_2_1
#print axioms E1UnitPurityDraft.unit31_mixed
#print axioms E1UnitPurityDraft.pencilA_nonzero
#print axioms E1UnitPurityDraft.pencilCross_zero
#print axioms E1UnitPurityDraft.pencilC2_zero
#print axioms E1UnitPurityDraft.u2_mixed
#print axioms E1UnitPurityDraft.witness51
#print axioms E1UnitPurityDraft.witness23
#print axioms E1UnitPurityDraft.witness32
#print axioms E1UnitPurityDraft.kl_fail_2_2
#print axioms E1UnitPurityDraft.kl_fail_5_1
#print axioms ExtensionShadow.probe_phase_instances
#print axioms ExtensionShadow.schwarz_witness_pairing
#print axioms ExtensionShadow.mirror_product_one
#print axioms ExtensionShadow.finite_breaking_16
#print axioms FlatnessShadow.trace_endpoints
#print axioms FlatnessShadow.dim_law_odd
#print axioms FlatnessShadow.dim_law_place2
#print axioms FourthVisitShadow.root_fourth_power
#print axioms FourthVisitShadow.square_root_family
#print axioms FourthVisitShadow.family_instances
#print axioms FrameBoundaryShadow.nativity_arithmetic
#print axioms FrameBoundaryShadow.uline_witnesses
#print axioms FrameBoundaryShadow.limit_frame_arithmetic
#print axioms GroupRingGlue.coupling_23
#print axioms GroupRingGlue.coupling_235
#print axioms GroupRingGlue.star_c2
#print axioms GroupRingGlue.star_c3
#print axioms GroupRingGlue.star_c5
#print axioms GroupRingGlue.star_coupling
#print axioms GroupRingGlue.class_relation
#print axioms GroupRingGlue.spectrum_psi0
#print axioms GroupRingGlue.spectrum_psi
#print axioms GroupRingGlue.spectrum_invertible
#print axioms GroupRingGlue.star_involutive
#print axioms H1Mechanism.one_ideal_per_norm
#print axioms H1Mechanism.h1_form_sum_of_squares
#print axioms InequalityShadow.quotient_below_weil
#print axioms InequalityShadow.strictness_gap
#print axioms KLSilence.foldSum_zero
#print axioms KLSilence.silence_of_ball_touching
#print axioms KLSilence.nonsilent_count
#print axioms KLSilence.countNonzero_eq
#print axioms KLSilence.offball_enumeration
#print axioms KLSilence.countNonzero_list_agreement
#print axioms KLSilence.banked_instances
#print axioms LefschetzShadow.pi_locus_and_pair
#print axioms LefschetzShadow.pi_phase_instances
#print axioms LefschetzShadow.dims_from_center
#print axioms LefschetzShadow.m3_locus_phase
#print axioms LinkShadow.twisted_row_silence
#print axioms LinkShadow.witness_no_fixed_point
#print axioms LinkShadow.witness_exchange_involution
#print axioms MechanismShadow.collapse_to_one_density
#print axioms MechanismShadow.one_density_two_windows
#print axioms MechanismShadow.sector_numerators_cancel
#print axioms MetaplecticRootShadow.u_gauss_eigen
#print axioms MetaplecticRootShadow.parity_and_sign
#print axioms MetaplecticRootShadow.square_root_obstruction
#print axioms NeitherPolesNorZeros.ball_orthogonal_21
#print axioms NeitherPolesNorZeros.ball_orthogonal_31
#print axioms NeitherPolesNorZeros.unit_action_neg
#print axioms NeitherPolesNorZeros.unit_average_zero
#print axioms NeitherPolesNorZeros.escape_witness_nonzero
#print axioms NormalizationForced.volume_factor_2
#print axioms NormalizationForced.volume_factor_3
#print axioms NormalizationForced.dim_ratio_not_gram
#print axioms NormalizationForced.identity_coeff_climbs_2
#print axioms NormalizationForced.identity_coeff_climbs_3
#print axioms OddPInstances.trace_silence_5
#print axioms OddPInstances.trace_silence_7
#print axioms OddPInstances.sonin_dims_odd
#print axioms OddPairingShadow.odd_pairing_imaginary
#print axioms OddPairingShadow.even_pairing_real
#print axioms OddPairingShadow.seed_pairing_instances
#print axioms OddPairingShadow.odd_weights_table
#print axioms OddPairingShadow.odd_collapse
#print axioms OrbitDictionary.twisted_silence
#print axioms OrbitDictionary.fiber_two
#print axioms OrbitDictionary.fiber_three
#print axioms OrbitDictionary.channels_distinct
#print axioms OrbitDictionary.no_fixed_offzero
#print axioms OrbitDictionary.shell_shift_2
#print axioms OrbitDictionary.shell_shift_3
#print axioms OrientationShadow.conj_fixes_real_flips_imaginary
#print axioms OrientationShadow.twin_conjugate_sum_real
#print axioms OrientationShadow.real_functionals_agree_on_the_orbit
#print axioms PairingShadow.flat_kills_twists
#print axioms PairingShadow.form_level_lift
#print axioms PairingShadow.dead_cell_power_traces
#print axioms PhasePlaneShadow.fixed_locus_instances
#print axioms PhasePlaneShadow.stationary_trace_instances
#print axioms PhasePlaneShadow.freeness_flatness_instances
#print axioms PhasePlaneShadow.center_seed_instances
#print axioms PhasePlaneShadow.scaling_instances
#print axioms PlancherelShadow.parseval_delta_2_1
#print axioms PlancherelShadow.parseval_delta_3_1
#print axioms PlancherelShadow.parseval_delta_2_2
#print axioms PlancherelShadow.parseval_delta_5_1
#print axioms PlancherelShadow.e1_sector_specialization
#print axioms PlancherelShadow.discrepancy_scaling
#print axioms PlancherelShadow.trace_scaling
#print axioms PlancherelShadow.p1_constant_instances
#print axioms ProductLawShadow.conjugate_balance_real
#print axioms ProductLawShadow.finite_balance_instance
#print axioms ProductMinusSumShadow.banked_instances
#print axioms ProductMinusSumShadow.odd_only_two
#print axioms ProductMinusSumShadow.odd_only_three
#print axioms ProductMinusSumShadow.place2_two
#print axioms ProductMinusSumShadow.place2_three
#print axioms ProductMinusSumShadow.anatomy_assembled
#print axioms QuotientLemmaShadow.dim_Vinv
#print axioms QuotientLemmaShadow.class_partition
#print axioms QuotientLemmaShadow.trace_counts
#print axioms QuotientLemmaShadow.preimage_count
#print axioms QuotientWeilShape.closed_form_integers
#print axioms QuotientWeilShape.shape_climbs_2
#print axioms QuotientWeilShape.shape_climbs_3
#print axioms QuotientWeilShape.ball_absorption
#print axioms RadializationShadow.shell_partition_instances
#print axioms RadializationShadow.transfer_shift_gcd_law
#print axioms RadializationShadow.ball_boundary_address
#print axioms RadializationShadow.theta_by_shells
#print axioms RadializationShadow.plane_factorization
#print axioms RigidityShadow.walk_constant
#print axioms RigidityShadow.fourth_root_instantiation
#print axioms RigidityShadow.fourth_root_discreteness
#print axioms RigidityShadow.tower_walk_instances
#print axioms SectorArithmetic.flat_n1
#print axioms SectorArithmetic.flat_n2
#print axioms SectorArithmetic.flat_n3
#print axioms SectorArithmetic.flat_n4
#print axioms SectorArithmetic.p2_instances
#print axioms SectorArithmetic.precell_all_zero
#print axioms SectorArithmetic.sig_cell_3
#print axioms SectorArithmetic.sig_cell_4
#print axioms SectorArithmetic.sig_cell_8
#print axioms SectorArithmetic.sig_cell_9
#print axioms SectorArithmetic.sig_cell_5_fourplace
#print axioms SectorArithmetic.sig_cell_9_fourplace
#print axioms SectorArithmetic.arrival_multiplies_16
#print axioms SectorArithmetic.pos_eq_neg_all
#print axioms SectorArithmetic.class_death_and_revival
#print axioms SilenceOnlyIfShadow.orbit_four_periodicity
#print axioms SilenceOnlyIfShadow.degenerate_center_vanishes
#print axioms SilenceOnlyIfShadow.witness_certificates_2_2
#print axioms StaircaseAddresses.address_law
#print axioms StaircaseAddresses.arrival_dead
#print axioms StaircaseAddresses.weight_death_law
#print axioms StaircaseAddresses.prime_free_window
#print axioms StaircaseAddresses.apexes_are_addresses
#print axioms StaircaseAddresses.full_weight_first_alive
#print axioms TensorSquareShadow.interleaving_index_law
#print axioms TensorSquareShadow.sector_pattern_gap
#print axioms ThetaBridgeShadow.point_count_identity
#print axioms ThetaBridgeShadow.cusp_count_instances
#print axioms ThetaBridgeShadow.transformation_shadow_odd
#print axioms ThetaContinuationShadow.center_exit_instances
#print axioms ThetaContinuationShadow.non_stabilization_witness
#print axioms ThetaContinuationShadow.orientation_break
#print axioms ThetaShadow.defect_gate_instances
#print axioms ThetaShadow.model_trace_silence
#print axioms ThetaShadow.seed_boundary_address
#print axioms TowerInstance.support_ball_vanish
#print axioms TowerInstance.hat_ball_vanish
#print axioms TowerInstance.iota_isometry_integer
#print axioms TowerInstance.gram_level_stability
#print axioms TowerInstance.fifth_law_integers
#print axioms TowerLimitShadow.embedding_instance
#print axioms TowerLimitShadow.intertwining_instance
#print axioms TowerLimitShadow.constancy_instances
#print axioms TowerLimitShadow.register_arithmetic
#print axioms TowerMonotoneShadow.ball_pullback
#print axioms TowerMonotoneShadow.inner_sum_rule
#print axioms TowerMonotoneShadow.transform_index_shift
#print axioms TowerMonotoneShadow.quotient_in_ball
#print axioms TraceSilence.trace_silence_2_1
#print axioms TraceSilence.trace_silence_2_2
#print axioms TraceSilence.trace_silence_2_3
#print axioms TraceSilence.trace_silence_3_1
#print axioms TraceSilence.trace_silence_3_2
#print axioms TraceSilence.trace_identity_dim
#print axioms TwistedRootShadow.eighth_root_pairing
#print axioms TwistedRootShadow.scalar_root_on_eigenvector
#print axioms TwistedShadow.mixed_pattern_counts
#print axioms TwistedShadow.tower_witness_pure
#print axioms TwistedShadow.tower_witness_in_Ei
#print axioms ValueShadow.equal_magnitude_lemma
#print axioms ValueShadow.finite_twin_instances
#print axioms ValueShadow.ledger_sum_conjugate
#print axioms WindowShadow.excess_sector_instances
#print axioms WindowShadow.line_address_instances
#print axioms WindowShadow.gauge_reading_pair
#print axioms SignTransferShadow.control_pos
#print axioms SignTransferShadow.control_neg
#print axioms SignTransferShadow.signs_distinct
#print axioms SignTransferShadow.eq_of_mul_pos
#print axioms SignTransferShadow.transfer
#print axioms SignTransferShadow.transfer_symm
#print axioms SignTransferShadow.neg_is_sign
#print axioms SignTransferShadow.sq_pos
#print axioms SignTransferShadow.flip_alternates
#print axioms SignTransferShadow.flip_is_sign
#print axioms SignTransferShadow.flip_pos
#print axioms SignTransferShadow.transfer_nonvacuous
